---

# .NET Core
language: csharp
mono: none
dotnet: 5.0.100
solution: OpenWorker.sln

# OS environment
dist: bionic

# Build matrix (OS, compiler)
matrix:
  include:
    - name: "Linux"
      os: linux
    - name: "MacOS"
      os: osx
      osx_image: xcode12.2

# Build scripts
script:
  - mv ow.Framework/config/commonsettings.example.json ow.Framework/config/commonsettings.json

  - touch ow.Framework/config/appsettings.json
  - touch ow.Framework.Tests/config/appsettings.json
  - touch ow.Service.District/config/appsettings.json
  - touch ow.Service.World/config/appsettings.json
  - touch ow.Utils.ItemView.Generator/config/appsettings.json

  - dotnet restore
  - dotnet build
